### PR TITLE
Add aka.ms/places

### PR DESCRIPTION
**Pull request by PowerBugi**
Forgot about the aka.ms link... 😄

### CODE REVIEW

**Comment by adamfowlerit** [comment]
@PowerBugi Thank you! Change is missing a closing bracket, wanna give it another shot otherwise I'll sort it out? :)

**Review by PowerBugi — COMMENTED** [review]
Just add the bracket and done a "Format document" in vscode to correct all indentation of the whole file

**Comment by PowerBugi** [comment]
Maybe it's too much, i did the fix and format the document, it's better now 😄

**Comment by adamfowlerit** [comment]
There we go, all good! Thanks again @PowerBugi  :)

**Pull request merged**
