### PR TITLE
Add Microsoft365DSC and Valimail

### PR DESCRIPTION
**Pull request by nathanmcnulty**

### CODE REVIEW

**Review by adamfowlerit — APPROVED** [review]

**Comment by PsychoData** [comment]
@nathanmcnulty  Is Valimail offered by Microsoft? Why should we include Valimail and not other Dmarc reporting providers like Dmarcian or PowerDmarc?

**Comment by PsychoData** [comment]
for example, I can see [references to Dmarcian](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#:~:text=Use%20the%20checklist%20at%20dmarcian) on a Microsoft Docs site. but cannot find reference to Valimail directly. 

We could include a reference to the MISA (Microsoft Intelligent Security Association) for [DMARC](https://www.microsoft.com/misapartnercatalog?IntegratedProducts=DMARCReportingforOffice365) which includes Valimail, Dmarcian, OnDmarc and others - but should we be encouraging specific vendor products over others by listing them on the 3rd party site?

**Comment by nathanmcnulty** [comment]
@PsychoData The additions were pulled from a conversation on Twitter. I'm personally not a fan of ValiMail, but they do have a partnership with Microsoft unlike the others: https://www.microsoft.com/security/blog/2021/09/01/get-free-dmarc-visibility-with-valimail-authenticate-and-microsoft-office-365/

Please, absolutely remove if it's not a good addition or creates conflict. I was simply contributing as I had promised in that thread ;)

**Comment by adamfowlerit** [comment]
I approved Valimail because of that partnership and that they provide a free tier of DMARC. MS doesn't have this natively. Definitely gets into a grey area, if they dropped their free tier they'd go.

**Comment by PsychoData** [comment]
Sure, I know Dmarcian at least also offers a free tier - though aimed at personal, not business, domains 
and @nathanmcnulty that is a _guest_ blog about an offering from the MISA I mentioned above, which also has offers from other MISA Partners like Dmarcian, Agari, and Red Sift offers as well as a Valimail offering . 

But anyone could offer DMARC Monitoring - honestly - it's just a few DNS Records and parsing some files, it's not really a special "partnership" from Valimail besides just being registered _as_ and MS Partner - Valimail Monitor is just a free product meant to tease their paid version Valimail Enforce / Authenticate or whatever it is called. I think they might have rebranded Enforce to Authenticate & added more focus on Brand Identity (BIMI) as well 

[MISA Dmarc Reporting Partners](https://www.microsoft.com/misapartnercatalog?IntegratedProducts=DMARCReportingforOffice365)

image

**Comment by PsychoData** [comment]
oh lordy - they'll let you delegate the entire _dmarc subdomain to them 
image
image

**Pull request merged**
