### PR TITLE
Update us-govt.json

### PR DESCRIPTION
**Pull request by SamErde**
Removed a duplicate entry for the GCC High Power Platform admin portal.

### CODE REVIEW

**Comment by SamErde** [comment]
Sure , whatever works! Did I edit the wrong file?

**Comment by davidbmarker** [comment]
@SamErde, this pull request failed the validation of the JSON file. 

#217 Pull Request has an extra "]" at the end, a simple mistake (I have made many of them before on this site :) )

@adamfowlerit, please abandon this pull request. Thanks!

**Failed Pull Request**
      {
        "portalName": "Power Apps",
        "primaryURL": "https://high.admin.powerplatform.microsoft.us/environments?l=en-US",
        "note": "GCC High"
      }
    **]**
  },

**Correct Syntax**
      {
        "portalName": "Power Apps",
        "primaryURL": "https://high.admin.powerplatform.microsoft.us/environments?l=en-US",
        "note": "GCC High"
      },

**Comment by davidbmarker** [comment]
@SamErde, this pull request failed the validation of the JSON file. 

#217 Pull Request has an extra "]" at the end, a simple mistake (I have made many of them before on this site :) )

@adamfowlerit, please abandon this pull request. Thanks!

**Failed Pull Request**
      {
        "portalName": "Power Apps",
        "primaryURL": "https://high.admin.powerplatform.microsoft.us/environments?l=en-US",
        "note": "GCC High"
      }
    **]**
  },

**Correct Syntax**
      {
        "portalName": "Power Apps",
        "primaryURL": "https://high.admin.powerplatform.microsoft.us/environments?l=en-US",
        "note": "GCC High"
      },

**Comment by SamErde** [comment]
> @SamErde, this pull request failed the validation of the JSON file.
> 
> #217 Pull Request has an extra "]" at the end, a simple mistake (I have made many of them before on this site :) )
> 
> @adamfowlerit, please abandon this pull request. Thanks!
> 
> **Failed Pull Request** { "portalName": "Power Apps", "primaryURL": "https://high.admin.powerplatform.microsoft.us/environments?l=en-US", "note": "GCC High" } **]** },
> 
> **Correct Syntax** { "portalName": "Power Apps", "primaryURL": "https://high.admin.powerplatform.microsoft.us/environments?l=en-US", "note": "GCC High" },

Ah shoot, thanks for the follow-up! That's what I get for rushing/multi-tasking!

**Pull request closed without merging**
