### PR TITLE
Added Windows 365 Subscription URL (used in desktop app)

### PR DESCRIPTION
**Pull request by ajf8729**

### CODE REVIEW

**Comment by adamfowlerit** [comment]
I'm getting a 401 on https://rdweb.wvd.microsoft.com/api/arm/feeddiscovery ?

**Comment by ajf8729** [comment]
I guess it's not really a portal you access directly. It's the subscription feed URL you enter into the Remote Desktop app to automatically discover the W365 resources you can connect to.

**Comment by adamfowlerit** [comment]
Hrm that's an interesting one... does it really count as a portal, or would we need to start adding a bunch of other URLs like autodiscover, smtp etc if we did this?

**Comment by ajf8729** [comment]
🤷I came here to find it first, then got it from the W365 user portal.

**Comment by adamfowlerit** [comment]
I've created a new section for this type of URL, maybe it can have a better title...

Thanks!

**Comment by PsychoData** [comment]
> 🤷I came here to find it first, then got it from the W365 user portal.

I just set up email discovery on the domain and forget about it https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-email-discovery

**Pull request closed without merging**
