### PR TITLE
Updated short links

### PR DESCRIPTION
**Pull request by StChrist-MSFT**
Please update the shortlinks to reflect the new naming of ATP products and more

### CODE REVIEW

**Comment by adamfowlerit** [comment]
Do you have details on which ones need updating?

**Comment by StChrist-MSFT** [comment]
Hi Adam,

I tried to change it myself:
***@***.***D74CB6.EE24B1A0]

Did I mess up something in Lines 367-373 when adding the section “secondaryURLs”?

﻿ --
[Microsoft]
Stefan B. Christensen
Sr. Customer Engineer
Secure Infrastructure EMEA

È+45 4567 8360
• ***@***.******@***.***>
﻿
If you have any feedback<https://aka.ms/StefanBC/Feedback> about my work, please fill out the form to let me and my manager know

**Comment by adamfowlerit** [comment]
Hi Stefan,
I think so, I do that all the time - I let it run it's checks and it failed which is why I reverted the change. You're welcome to give it another shot 🙂


Thanks
Adam Fowler

Microsoft MVP - Office Apps and Services

https://www.adamfowlerit.com & https://msportals.io

[cid:7d0ea51a-dfc9-4d44-b7c5-0c5b99c5c400]

________________________________

**Comment by StChrist-MSFT** [comment]
Hi Adam,

Just went through the code and did JSON validation... all is good. So, it shouldn't be the code... when looking at the error message it says:
**_Error: fatal: couldn't find remote ref refs/pull/128/merge_**

So is something else causing this error?

﻿ --
[Microsoft]
Stefan B. Christensen
Sr. Customer Engineer
Secure Infrastructure EMEA

**Comment by StChrist-MSFT** [comment]
I have tried to split it up into two requests... the first one #131 and is just a change or URL. The second one is on the way and will add aka.ms links til MCAS...

**Comment by adamfowlerit** [comment]
OK they both passed and are now live 🙂 Thanks for doing this!


Thanks
Adam Fowler

Microsoft MVP - Office Apps and Services

https://www.adamfowlerit.com & https://msportals.io

[cid:4631c1e4-c942-4b97-a949-5a65c1d0e7a6]

________________________________

**Comment by StChrist-MSFT** [comment]
No worries. Glad I could contribute! 😉👍

**Pull request merged**
